services:
  - type: web
    name: bawi-studio-frontend
    env: node
    plan: free
    buildCommand: npm run build
    startCommand: npm run preview
    envVars:
      - key: VITE_API_URL
        value: https://bawi-studio-backend.onrender.com
