services:
  - type: web
    name: bawi-studio-backend
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: SUPABASE_URL
        scope: build
      - key: SUPABASE_KEY
        scope: build
      - key: JWT_SECRET
        scope: build
      - key: ADMIN_PASSWORD_HASH
        scope: build
      - key: PORT
        value: 10000
